version: "3.7"
services:
  webapp:
    image: app:latest
    build:
      context: ./app
      dockerfile: Dockerfile    
    ports:
      - 8888:8080
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8888"]
      interval: 1m30s
      timeout: 20s
      retries: 5
      start_period: 1m
  testframework:
    image: cypress
    build: ./cypress_docker
    container_name: cypress
    depends_on:
      - webapp
    environment:
      - CYPRESS_baseUrl=http://webapp:8080
    #command: bash
    volumes:
      - "./cypress_docker/cypress:/app/cypress:rw"
    #command: npx cypress open
    command: npx cypress run
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 300s

